# Generated by Django 5.0.3 on 2024-04-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftrides_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fullname',
            field=models.CharField(max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='account',
            name='phonenumber',
            field=models.CharField(max_length=100, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='dateofbirth',
            field=models.DateField(null=True, verbose_name='Date Of Birth'),
        ),
    ]
