# Generated by Django 5.0.3 on 2024-04-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftrides_app', '0004_alter_account_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='location',
            new_name='pickup_location',
        ),
    ]
