# Generated by Django 5.0.3 on 2024-04-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftrides_app', '0005_rename_location_reservation_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dropoff',
            field=models.DateTimeField(verbose_name='Dropoff Date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup',
            field=models.DateTimeField(verbose_name='Pickup Date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_location',
            field=models.CharField(max_length=100, verbose_name='Pickup Location'),
        ),
    ]
