# Generated by Django 5.0.3 on 2024-04-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftrides_app', '0006_alter_reservation_dropoff_alter_reservation_pickup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(null=True, verbose_name='Pickup Time'),
        ),
    ]
