# Generated by Django 5.0.3 on 2024-04-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftrides_app', '0011_rename_payment_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
