# Generated by Django 5.0.3 on 2024-04-29 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftrides_app', '0015_transaction_reservation_alter_transaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('paystack_reference', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='swiftrides_app.reservation')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
