# Generated by Django 5.0.3 on 2024-04-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftrides_app', '0017_payment_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
