# Generated by Django 5.0.3 on 2024-03-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftrides_companies', '0002_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
