# Generated by Django 5.0.3 on 2024-03-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftrides_companies', '0003_remove_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='logo',
        ),
    ]
