# Generated by Django 5.0.3 on 2024-03-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftrides_companies', '0004_remove_customuser_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
