# Generated by Django 5.0.3 on 2024-03-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftrides_companies', '0005_customuser_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
