# Generated by Django 5.0.3 on 2024-03-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftrides_companies', '0006_car_price_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
