# Generated by Django 5.0.3 on 2024-03-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftrides_companies', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
