# Generated by Django 5.0.3 on 2024-03-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftrides_companies', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='companyname',
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Company Name'),
        ),
    ]
