# Generated by Django 5.0.3 on 2024-03-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftrides_companies', '0011_remove_profile_companyname_profile_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
